### ISSUE TITLE
[BE] C4 Model C2까지 그리기

### ISSUE THREAD

**Issue by ksundong** [codesquad-member-2020/airbnb-11#14]
C4 Model을 그려봅니다.

C1: System Context
C2: Container diagram

**Comment by ksundong** [comment]
C1 Model
![C1](https://i.imgur.com/dhisgFy.png)

**Comment by ksundong** [comment]
C2 Model
![C2](https://i.imgur.com/R2WkIIe.png)

**Comment by 102092** [comment]
짱짱맨입니다~!! 오늘 얘기 나누면서 모호했던 부분이 확실해지네요!
