### ISSUE TITLE
[BE] DB에 위도, 경도 컬럼 추가하기

### ISSUE THREAD

**Issue by ksundong** [codesquad-member-2020/airbnb-11#25]
위치를 저장할 위도, 경도 컬럼을 추가합니다.

**Comment by 102092** [comment]
위도 경도도 필요한가요...?

**Comment by ksundong** [comment]
넵 Pin 찍는거 해보신데요!

**Comment by ksundong** [comment]
https://stackoverflow.com/questions/159255/what-is-the-ideal-data-type-to-use-when-storing-latitude-longitude-in-a-mysql/27926894
