### ISSUE TITLE
[BE] Infra 구성

### ISSUE THREAD

**Issue by ksundong** [codesquad-member-2020/airbnb-11#4]
- 어떤 서버를 Test로 할지 배포 서버로 할 지
  - Test: dev브랜치 push될 때 마다 배포되도록 --> @102092 
  - Production: master브랜치 push 될 때 마다 배포되도록 --> @ksundong 

---

- Infra Architecture
  - VPC
    - 서버, DB 서브넷 분리
  - EC2
     - nginx
  - RDS

**Comment by ksundong** [comment]
http://13.124.223.191

**Comment by 102092** [comment]
- [http://3.232.101.173/](http://3.232.101.173/)

**Comment by 102092** [comment]
- 위에 작성된 infra 설정을 반영한 서버를 배포하였음
- master : 13.124.223.191
- dev : 3.232.101.173
