### ISSUE TITLE
[BE]  필요한 Mock 추가

### ISSUE THREAD

**Issue by 102092** [codesquad-member-2020/airbnb-11#40]
- 기능 구현에 필요한 Mock 데이터를 추가적으로 넣는다.
- 추천 10~15개
- Paging구현을 테스트 해야 한다면, 더 넣어야 할듯.

**Comment by ksundong** [comment]
적어도 50개는 만들어야 할 것 같습니다. ㅎㅎㅎㅎ
최종적으로 목표는 한 1000개 정도는 필요할 듯 해요.
