### ISSUE TITLE
[BE] Phase1 리뷰

### ISSUE THREAD

**Issue by 102092** [codesquad-member-2020/airbnb-11#63]
- [x] CD에서 AWS CodeDeploy를 활용하도록 수정 --> #64
- [x] 코딩 컨벤션 확실히하기 --> IDE 자동정렬 따라가기
- [ ] ApiError 클래스 리팩토링 --> @ksundong 
- [x] 클라이언트측 요청 오류일 때 logging level을 error에서 낮추기 --> @102092 
- [x] deploy.sh 수정하기 -> @102092 
   - [x] dev-be-phase2 pull-request CI
   - [x] test application.yml host 추가
   - [x] CD bootjar

**Comment by ksundong** [comment]
의문점이 있어서 질문 남겨놨습니다.
리팩토링 하지 않을 수도 있을 것 같아요!
